# version: '3'
# services:
#   mongodb:
#     container_name: mongodb
#     image: mongo:latest
#     ports:
#       - '27017:27017'
#   app:
#     container_name: docker-node-mongo
#     build:
#         context: .
#         dockerfile: Dockerfile
#     # ports:
#     #   - '8081:8081'
#     environment:
#       - DB_URI=mongodb://127.0.0.1:27017/NodeApi
#       - PRIVATE_KEY='this is not about glory'
#     links:
#       - mongodb
#     restart: on-failure



version: '3'
services:
    mongodb:
        container_name: mongodb
        image : mongo:latest
        environment:
        - PUID=1000
        - PGID=1000
        ports:
        - 27017:27017
        restart: unless-stopped
    app:
        container_name: node-express
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DB_URI='mongodb://mongodb:27017/NodeApi'
        ports:
            - '8081:8081'
        depends_on:
            - mongodb




